apiVersion: v1
kind: Pod
metadata:
  name: tcpsocket-echo 
  namespace: policy-demo
  labels:
    run: tcpsocket-echo
spec:
  containers:
  - image: docker.io/sunausti/tcp-echoserver
    imagePullPolicy: IfNotPresent
    name:
      tcpsocket-echo
    ports:
      - containerPort: 1237
    readinessProbe:
      tcpSocket:
        port: 1237
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: tcpsocket-echo
  namespace: policy-demo
  labels:
    run: tcpsocket-echo
spec:
  selector:
    run: tcpsocket-echo
  ports:
  - protocol: TCP
    port: 1237
    targetPort: 1237
